/** Declaration file generated by dts-gen */

import { Observable } from 'rxjs';

export class Model {
    constructor(attributes: { [key: string]: any });

    get(key: string): any;

    get$(key: string): Observable<any>;

    set(key: string, value: any);

    toJS(): Object;

}

type Constructor<T extends Model> = new (...args: any[]) => T;
export function createModel<T extends Constructor<any>>(opts: {[name: string]: any}): T;
